local C, G = unpack(Cobalt)
local SM = C:GetModule('SharedMedia')
local LSM = C.Libs.LSM

-- =====================================================
-- Fonts
-- =====================================================
LSM:Register("font", "Gotham Narrow Ultra", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\Gotham Narrow Ultra.otf")
LSM:Register("font", "Avant Garde Bold", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\ITC Avant Garde Gothic Bold.otf")
LSM:Register("font", "Avant Garde Medium", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\ITC Avant Garde Gothic Medium.otf")
LSM:Register("font", "TeX Bold", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\texgyreadventor-bold.otf")
LSM:Register("font", "TeX Bold Italic", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\texgyreadventor-bolditalic.otf")
LSM:Register("font", "TeX Italic", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\texgyreadventor-italic.otf")
LSM:Register("font", "TeX Regular", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\texgyreadventor-regular.otf")
LSM:Register("font", "Naowh", "Interface\\AddOns\\Cobalt\\Media\\Fonts\\Naowh.otf")

-- =====================================================
-- StatusBars
-- =====================================================
LSM:Register("statusbar", "ArrowGlow", "Interface\\AddOns\\Cobalt\\Media\\Textures\\ArrowGlow.tga")
LSM:Register("statusbar", "ArrowGlowSmall", "Interface\\AddOns\\Cobalt\\Media\\Textures\\ArrowGlowSmall.tga")
LSM:Register("statusbar", "Atrocity", "Interface\\AddOns\\Cobalt\\Media\\Textures\\Atrocity.tga")
LSM:Register("statusbar", "BuiOnePixel", "Interface\\AddOns\\Cobalt\\Media\\Textures\\BuiOnePixel.tga")
LSM:Register("statusbar", "BuiOnePixel2", "Interface\\AddOns\\Cobalt\\Media\\Textures\\BuiOnePixel2.tga")
LSM:Register("statusbar", "BuiOnePixel3", "Interface\\AddOns\\Cobalt\\Media\\Textures\\BuiOnePixel3.tga")
LSM:Register("statusbar", "NaowhLeft", "Interface\\AddOns\\Cobalt\\Media\\Textures\\NaowhLeft.tga")
LSM:Register("statusbar", "NaowhRight", "Interface\\AddOns\\Cobalt\\Media\\Textures\\NaowhRight.tga")
LSM:Register("statusbar", "ElvUI Blank", "Interface\\AddOns\\Cobalt\\Media\\Textures\\White8x8.tga")
LSM:Register("statusbar", "Kait", "Interface\\AddOns\\Cobalt\\Media\\Textures\\Kait.tga")

-- =====================================================
-- Sounds
-- =====================================================
LSM:Register("sound", "Info", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Info.ogg")
LSM:Register("sound", "1 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\1.ogg")
LSM:Register("sound", "2 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\2.ogg")
LSM:Register("sound", "3 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\3.ogg")
LSM:Register("sound", "4 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\4.ogg")
LSM:Register("sound", "5 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\5.ogg")
LSM:Register("sound", "6 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\6.ogg")
LSM:Register("sound", "7 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\7.ogg")
LSM:Register("sound", "8 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\8.ogg")
LSM:Register("sound", "9 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\9.ogg")
LSM:Register("sound", "10 -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\10.ogg")
LSM:Register("sound", "Absorb -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Absorb.ogg")
LSM:Register("sound", "Add -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Add.ogg")
LSM:Register("sound", "Adds -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Adds.ogg")
LSM:Register("sound", "AoE -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\AoE.ogg")
LSM:Register("sound", "Avoid -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Avoid.ogg")
LSM:Register("sound", "Bait -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Bait.ogg")
LSM:Register("sound", "Beam -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Beam.ogg")
LSM:Register("sound", "Behind -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Behind.ogg")
LSM:Register("sound", "Bloodlust -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Bloodlust.ogg")
LSM:Register("sound", "Bomb -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Bomb.ogg")
LSM:Register("sound", "Breath -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Breath.ogg")
LSM:Register("sound", "Buff -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Buff.ogg")
LSM:Register("sound", "CC -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\CC.ogg")
LSM:Register("sound", "Charge -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Charge.ogg")
LSM:Register("sound", "Clear In -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Clear In.ogg")
LSM:Register("sound", "Clear -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Clear.ogg")
LSM:Register("sound", "Collect -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Collect.ogg")
LSM:Register("sound", "Combat -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Combat.ogg")
LSM:Register("sound", "Dance -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Dance.ogg")
LSM:Register("sound", "Debuff -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Debuff.ogg")
LSM:Register("sound", "Destroy -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Destroy.ogg")
LSM:Register("sound", "Dispell -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Dispell.ogg")
LSM:Register("sound", "Dodge Inc -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Dodge Inc.ogg")
LSM:Register("sound", "Dodge -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Dodge.ogg")
LSM:Register("sound", "Dot -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Dot.ogg")
LSM:Register("sound", "External -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\External.ogg")
LSM:Register("sound", "Fixate -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Fixate.ogg")
LSM:Register("sound", "Freedom -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Freedom.ogg")
LSM:Register("sound", "Frontal -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Frontal.ogg")
LSM:Register("sound", "Green -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Green.ogg")
LSM:Register("sound", "Hide -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Hide.ogg")
LSM:Register("sound", "High Stacks -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\High Stacks.ogg")
LSM:Register("sound", "Immune -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Immune.ogg")
LSM:Register("sound", "In -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\In.ogg")
LSM:Register("sound", "Inc -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Inc.ogg")
LSM:Register("sound", "Inside -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Inside.ogg")
LSM:Register("sound", "Intermission -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Intermission.ogg")
LSM:Register("sound", "Kick -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Kick.ogg")
LSM:Register("sound", "Knock -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Knock.ogg")
LSM:Register("sound", "Left -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Left.ogg")
LSM:Register("sound", "Linked -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Linked.ogg")
LSM:Register("sound", "LoS -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\LoS.ogg")
LSM:Register("sound", "Melee -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Melee.ogg")
LSM:Register("sound", "Mount -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Mount.ogg")
LSM:Register("sound", "Move -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Move.ogg")
LSM:Register("sound", "Next -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Next.ogg")
LSM:Register("sound", "Nuke -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Nuke.ogg")
LSM:Register("sound", "Orb -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Orb.ogg")
LSM:Register("sound", "Out -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Out.ogg")
LSM:Register("sound", "Pull -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Pull.ogg")
LSM:Register("sound", "Push -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Push.ogg")
LSM:Register("sound", "Ready -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Ready.ogg")
LSM:Register("sound", "Red -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Red.ogg")
LSM:Register("sound", "Reflect -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Reflect.ogg")
LSM:Register("sound", "Right -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Right.ogg")
LSM:Register("sound", "Run -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Run.ogg")
LSM:Register("sound", "Sac -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Sac.ogg")
LSM:Register("sound", "Shield -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Shield.ogg")
LSM:Register("sound", "Soak -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Soak.ogg")
LSM:Register("sound", "Spike -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Spike.ogg")
LSM:Register("sound", "Spread -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Spread.ogg")
LSM:Register("sound", "Stack -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Stack.ogg")
LSM:Register("sound", "Stop -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Stop.ogg")
LSM:Register("sound", "Stop Cast -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Stop Cast.ogg")
LSM:Register("sound", "Switch -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Switch.ogg")
LSM:Register("sound", "Taunt -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Taunt.ogg")
LSM:Register("sound", "Totem -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Totem.ogg")
LSM:Register("sound", "Trap -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Trap.ogg")
LSM:Register("sound", "Turn -Naowh", "Interface\\AddOns\\Cobalt\\Media\\Sounds\\Turn.ogg")

function SM:OnEnable()
    C:Debug(self, C.MODULE_ENABLED)
end
